### PR TITLE
Change adress miner.py

### PR DESCRIPTION
**Pull request by Shpinut**

### CODE REVIEW

**Review by jacklevin74 — COMMENTED** [review]
useless

**Comment by hannescrypto** [comment]
dear jack, it would be really nice to move the address loaction to a ethaddress.txt located in the folder, because its quite a pain in the a.. to bring these files via command tools like nano up to date (so change your eth address for our eth address), and how often there are coming updates, its really a husle to keep up getting the latest files right

**Comment by svveaty** [comment]
@hannescrypto you can do:
git stash
git pull
git stash pop

that's it, no nano required

**Comment by jacklevin74** [comment]
it makes sense in the later release I'll setup config.conf file to do that

**Comment by hannescrypto** [comment]
> it makes sense in the later release I'll setup config.conf file to do that

nice, thanks, i just finished my tool XENMINERLOADER V1.1, which now compatible with your new config.conf

would love to hear your feedback about the tool ;-)

**Comment by hannescrypto** [comment]
https://github.com/hannescrypto/XenMinerLoader

**Pull request closed without merging**
